application: myrivulet
version: 434
runtime: go
api_version: go1

inbound_services:
- warmup

handlers:
- url: /google05548b7e829ace4d.html
  static_files: google05548b7e829ace4d.html
  upload: google05548b7e829ace4d.html

- url: /rivulet.webapp
  static_files: rivulet.webapp
  mime_type: application/x-web-app-manifest+json
  upload: rivulet.webapp

- url: /rivulet.appcache
  static_files: rivulet.appcache
  upload: rivulet.appcache

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /(api|about|offline|extras)
  static_files: static/\1.html
  upload: static/(api|about|offline).html

- url: /bootstrap
  static_dir: bootstrap

- url: /font-awesome/font
  static_dir: font-awesome/font
  mime_type: application/octet-stream

- url: /font-awesome/css
  static_dir: font-awesome/css
  mime_type: text/css

- url: /static
  static_dir: static

- url: /
  script: _go_app
  login: optional

- url: /logout
  script: _go_app
  login: optional

- url: /login
  script: _go_app
  login: optional

- url: /app
  script: _go_app
  login: required

- url: /article
  script: _go_app
  login: required

- url: /feed
  script: _go_app
  login: required

- url: /user
  script: _go_app
  login: required

- url: /refresh
  script: _go_app
  login: admin

- url: /_ah/warmup
  script: _go_app
  login: admin

- url: /_ah/queue/go/delay
  script: _go_app
  login: admin
