application: myrivulet
version: 250
runtime: go
api_version: go1

inbound_services:
- warmup

handlers:
- url: /google05548b7e829ace4d.html
  static_files: google05548b7e829ace4d.html
  upload: google05548b7e829ace4d.html

- url: /(rivulet.appcache)
  static_files: \1
  upload: rivulet.appcache

- url: /(robots.txt)
  static_files: \1
  upload: robots.txt

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /(api|about|offline)
  static_files: static/\1.html
  upload: static/(api|about|offline).html

- url: /font-awesome/font
  static_dir: font-awesome/font
  mime_type: application/octet-stream

- url: /font-awesome/css
  static_dir: font-awesome/css
  mime_type: text/css

- url: /static
  static_dir: static

- url: /
  script: _go_app
  login: required

- url: /logout
  script: _go_app
  login: optional

- url: /login
  script: _go_app
  login: optional

- url: /article
  script: _go_app
  login: required

- url: /feed
  script: _go_app
  login: required

- url: /user
  script: _go_app
  login: required

- url: /refresh
  script: _go_app
  login: admin

- url: /_ah/warmup
  script: _go_app
  login: admin

- url: /_ah/queue/go/delay
  script: _go_app
  login: admin
