application: myrivulet
version: 142
runtime: go
api_version: go1

handlers:
- url: /(rivulet.appcache)
  static_files: \1
  upload: rivulet.appcache

- url: /(robots.txt)
  static_files: \1
  upload: robots.txt

- url: /(api|about|offline)
  static_files: \1.html
  upload: (api|about|offline).html

- url: /font-awesome/font
  static_dir: font-awesome/font
  mime_type: application/octet-stream

- url: /font-awesome/css
  static_dir: font-awesome/css
  mime_type: text/css

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /logo.png
  static_files: logo.png
  upload: logo.png

- url: /static
  static_dir: static

- url: /.*
  script: _go_app
