application: myrivulet
version: 106
runtime: go
api_version: go1.1beta

handlers:
- url: /(.*\.(css|json|svg|appcache|gif|png|jpg|js|ico))
  static_files: \1
  upload: (.*\.(css|json|svg|appcache|gif|png|jpg|js|ico))

- url: /(.*\.(coffee))
  static_files: \1
  mime_type: text/x-coffeescript
  upload: (.*\.(coffee))

- url: /.*
  script: _go_app
