application: myrivulet
version: 587
runtime: go
api_version: go1

inbound_services:
- warmup

handlers:
- url: /google05548b7e829ace4d.html
  static_files: google05548b7e829ace4d.html
  upload: google05548b7e829ace4d.html

- url: /rivulet.webapp
  static_files: static/rivulet.webapp
  mime_type: application/x-web-app-manifest+json
  upload: static/rivulet.webapp

- url: /rivulet.appcache
  static_files: static/rivulet.appcache
  upload: static/rivulet.appcache

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /ga.js
  static_files: ga.js
  upload: ga.js

- url: /(api|about|offline|extras|help)
  static_files: build/\1.html
  upload: build/(api|about|offline|extras|help).html

- url: /script.js
  static_files: build/script.min.js
  upload: build/script.min.js

- url: /style.css
  static_files: build/style.min.css
  upload: build/style.min.css

- url: /logo.png
  static_files: static/logo.png
  upload: static/logo.png

- url: /icon.svg
  static_files: static/icon.svg
  upload: static/icon.svg

- url: /icon.png
  static_files: static/icon.png
  upload: static/icon.png

- url: /icon(.*).png
  static_files: build/icon\1.png
  upload: build/icon.*.png

- url: /jquery.js
  static_files: jquery.js
  upload: jquery.js

- url: /bootstrap
  static_dir: bootstrap

- url: /font-awesome/fonts
  static_dir: font-awesome/fonts

- url: /font-awesome/css
  static_dir: font-awesome/css

- url: /
  script: _go_app
  login: optional

- url: /logout
  script: _go_app
  login: optional

- url: /login
  script: _go_app
  login: optional

- url: /app
  script: _go_app
  login: required

- url: /article
  script: _go_app
  login: required

- url: /feed
  script: _go_app
  login: required

- url: /refresh
  script: _go_app
  login: admin

- url: /_ah/queue/go/delay
  script: _go_app
  login: admin

- url: /_ah/warmup
  script: _go_app
  login: admin
