application: myrivulet
version: 122
runtime: go
api_version: go1

handlers:
- url: /myrivulet.appcache
  static_files: myrivulet.appcache
  upload: myrivulet.appcache

- url: /font-awesome
  static_dir: font-awesome

- url: /static
  static_dir: static

- url: /.*
  script: _go_app
