application: myrivulet
version: 459
runtime: go
api_version: go1

inbound_services:
- warmup

handlers:
- url: /google05548b7e829ace4d.html
  static_files: google05548b7e829ace4d.html
  upload: google05548b7e829ace4d.html

- url: /rivulet.webapp
  static_files: static/rivulet.webapp
  mime_type: application/x-web-app-manifest+json
  upload: static/rivulet.webapp

- url: /rivulet.appcache
  static_files: static/rivulet.appcache
  upload: static/rivulet.appcache

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(api|about|offline|extras)
  static_files: build/\1.html
  upload: build/(api|about|offline|extras).html

- url: /script.js
  static_files: build/script.min.js
  upload: build/script.min.js

- url: /style.css
  static_files: build/style.min.css
  upload: build/style.min.css

- url: /logo.png
  static_files: static/logo.png
  upload: static/logo.png

- url: /icon(.*).png
  static_files: static/icon\1.png
  upload: static/icon.*.png

- url: /jquery.js
  static_files: jquery.js
  upload: jquery.js

- url: /jquery.map
  static_files: jquery.map
  upload: jquery.map

- url: /bootstrap
  static_dir: bootstrap

- url: /font-awesome
  static_dir: font-awesome

- url: /font-awesome/font/fontawesome-webfont.eot
  static_files: font-awesome/font/fontawesome-webfont.eot
  upload: font-awesome/font/fontawesome-webfont.eot
  mime_type: application/vnd.ms-fontobject

- url: /font-awesome/font/fontawesome-webfont.woff
  static_files: font-awesome/font/fontawesome-webfont.woff
  upload: font-awesome/font/fontawesome-webfont.woff
  mime_type: application/font-woff

- url: /
  script: _go_app
  login: optional

- url: /logout
  script: _go_app
  login: optional

- url: /login
  script: _go_app
  login: optional

- url: /app
  script: _go_app
  login: required

- url: /article
  script: _go_app
  login: required

- url: /feed
  script: _go_app
  login: required

- url: /user
  script: _go_app
  login: required

- url: /refresh
  script: _go_app
  login: admin

- url: /_ah/warmup
  script: _go_app
  login: admin
