#!/bin/bash

awk '/version: *[0-9]+/{$2++}1' app.yaml > app.yaml.new && mv app.yaml{.new,}
version=`sed -n 's/#\([0-9]*\)/\1/p' rivulet.appcache`
let version++
sed -i "s/#[0-9]*/#$version/" rivulet.appcache
