#!/bin/sh

export UNZIP=-o

MAP=jquery.map
wget 'http://code.jquery.com/jquery-2.0.2.min.js' -O jquery.js
wget 'http://code.jquery.com/jquery-2.0.2.min.map' -O $MAP
sed -i "s/sourceMappingURL=\(.*\)/sourceMappingURL=$MAP/" jquery.js

wget http://google-analytics.com/ga.js

wget 'http://twitter.github.io/bootstrap/assets/bootstrap.zip'
unzip bootstrap.zip
rm bootstrap.zip

cd bootstrap
wget 'http://bootstrap-server.jasny.net/bootstrap-fileupload.zip'
unzip bootstrap-fileupload.zip
rm bootstrap-fileupload.zip
cd ..

wget 'http://fortawesome.github.io/Font-Awesome/assets/font-awesome.zip'
unzip font-awesome.zip
rm font-awesome.zip

